/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import dataprocessors.GetDataFromJson;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.NFT;

/**
 *
 * @author quyetdaika
 */
public class Home extends javax.swing.JFrame implements GetDataFromJson {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        defaultTableModel = (DefaultTableModel)jTable1.getModel();
        nfts = getNFTsFromJson();
        btnTimeSlotClicked(btn1H.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jlbHome = new javax.swing.JLabel();
        jlbNFT = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        jtfSearch = new javax.swing.JTextField();
        btn1H = new javax.swing.JButton();
        btn6H = new javax.swing.JButton();
        btn24H = new javax.swing.JButton();
        btn7D = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(204, 204, 255));

        jlbHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbHome.setText("Home");

        jlbNFT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbNFT.setText("NFT");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbNFT)
                .addGap(191, 191, 191))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbHome)
                    .addComponent(jlbNFT))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Volume", "Change", "Floor price", "Owners", "Items"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setInheritsPopupMenu(true);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btn1H.setText("1H");
        btn1H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1HActionPerformed(evt);
            }
        });

        btn6H.setText("6H");
        btn6H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6HActionPerformed(evt);
            }
        });

        btn24H.setText("24H");
        btn24H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24HActionPerformed(evt);
            }
        });

        btn7D.setText("7D");
        btn7D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(btn1H, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6H, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn24H, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7D, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6H)
                    .addComponent(btn24H)
                    .addComponent(btn7D)
                    .addComponent(btn1H))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn6HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6HActionPerformed
        // TODO add your handling code here:
        btnTimeSlotClicked(btn6H.getText());
    }//GEN-LAST:event_btn6HActionPerformed

    private void btn24HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn24HActionPerformed
        // TODO add your handling code here:
        btnTimeSlotClicked(btn24H.getText());
    }//GEN-LAST:event_btn24HActionPerformed

    private void btn7DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7DActionPerformed
        // TODO add your handling code here:
        btnTimeSlotClicked(btn7D.getText());
    }//GEN-LAST:event_btn7DActionPerformed

    private void btn1HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1HActionPerformed
        // TODO add your handling code here:
        btnTimeSlotClicked(btn1H.getText());
    }//GEN-LAST:event_btn1HActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(jtfSearch.getText().equals("")) return;
        defaultTableModel.setRowCount(0);
        for(NFT x : currentNfts){
            if(x.getName().toLowerCase().contains(jtfSearch.getText().toLowerCase())) 
                defaultTableModel.addRow(x.getNFT());
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    
    private void btnTimeSlotClicked(String timeSlot){
        currentNfts = getNFTsByTimeslot(timeSlot);
        defaultTableModel.setRowCount(0);
        for(NFT x : currentNfts){
            defaultTableModel.addRow(x.getNFT());
        }
    }
    
    private List<NFT> getNFTsByTimeslot(String timeSlot){
        List<NFT> result = new ArrayList<>();
        for(NFT x : nfts){
            if(x.getTimeSlot().equals(timeSlot)) result.add(x);
        }
        return result;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    DefaultTableModel defaultTableModel;
    private List<NFT> currentNfts;
    private List<NFT> nfts;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1H;
    private javax.swing.JButton btn24H;
    private javax.swing.JButton btn6H;
    private javax.swing.JButton btn7D;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlbHome;
    private javax.swing.JLabel jlbNFT;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables
}
