/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewtest;

import models.Tweet;

/**
 *
 * @author quyetdaika
 */
public class TweetPanel extends javax.swing.JPanel {

    /**
     * Creates new form TweetPanel
     * @param tweet
     */
    public TweetPanel() {
        initComponents();
        
//        lbName.setText(tweet.getName());
//        lbUser.setText(tweet.getUser());
//        lbCreatedAt.setText(tweet.getCreatedAt());
//        jtaContent.setText(tweet.getContent());
//        lbComment.setText(tweet.getComment());
//        lbRetweet.setText(tweet.getRetweet());
//        lbLike.setText(tweet.getLike());
//        lbView.setText(tweet.getView());
    }
    
    public TweetPanel(Tweet tweet){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        lbCreatedAt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaContent = new javax.swing.JTextArea();
        lbComment = new javax.swing.JLabel();
        lbRetweet = new javax.swing.JLabel();
        lbView = new javax.swing.JLabel();
        lbLike = new javax.swing.JLabel();

        lbName.setText("name");

        lbUser.setText("username");

        lbCreatedAt.setText("createdAt");

        jtaContent.setColumns(20);
        jtaContent.setRows(5);
        jScrollPane1.setViewportView(jtaContent);

        lbComment.setText("comment");

        lbRetweet.setText("retweet");

        lbView.setText("view");

        lbLike.setText("like");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbName)
                        .addGap(38, 38, 38)
                        .addComponent(lbUser)
                        .addGap(18, 18, 18)
                        .addComponent(lbCreatedAt))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbComment)
                            .addGap(60, 60, 60)
                            .addComponent(lbRetweet)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbLike)
                            .addGap(64, 64, 64)
                            .addComponent(lbView))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(lbUser)
                    .addComponent(lbCreatedAt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComment)
                    .addComponent(lbRetweet)
                    .addComponent(lbView)
                    .addComponent(lbLike))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaContent;
    private javax.swing.JLabel lbComment;
    private javax.swing.JLabel lbCreatedAt;
    private javax.swing.JLabel lbLike;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbRetweet;
    private javax.swing.JLabel lbUser;
    private javax.swing.JLabel lbView;
    // End of variables declaration//GEN-END:variables
}
